config/routes.rb
Tuter::Application.routes.draw do  

  resources :reviews

  devise_for :users
  devise_scope :user do
    match "/users/sign_out" => "devise/sessions#destroy"
    match "/dashboard" => "dashboard#dashboard"
  end

  root :to => "home#index"

  # Android API routes
  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
      get 'tasks' => 'tasks#index', :as => 'tasks'
    end
  end

  resources :groups do
    resources :student_ids
    resources :tutor_ids
    resources :courses
  end

  resources :user
  resources :locations
  resources :search
  resources :organizations
  resources :programs

  resources :tutor_watchlist do
    resources :user
  end

  resources :home do
    member do 
      get 'search_tutors'
    end
  end

  resources :dashboard do
    collection do 
      post 'delete_group'
    end 
  end

  resources :day_availabilities
  
  resources :week_availabilities do
    resources :day_availabilities
    resources :day_availability
  end

  resources :reviews
  
  # Omniauth routes
  match '/users/auth/:provider/callback', to: 'sessions#create'
  match '/users/auth/failure', to: redirect('/')


  # User Signup Routes
  match "/user" => "user#user"
  match "/dashboard" => "home#index"

  # Organization List Page
  match "/organizations" => "organizations#index"
  
  match '/update_watchlist' => 'tutor_watchlist#update' 
 
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
 
  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

#== Route Map
# Generated on 06 May 2013 02:00
#
#                                          POST   /reviews(.:format)                                                               reviews#create
#                               new_review GET    /reviews/new(.:format)                                                           reviews#new
#                              edit_review GET    /reviews/:id/edit(.:format)                                                      reviews#edit
#                                   review GET    /reviews/:id(.:format)                                                           reviews#show
#                                          PUT    /reviews/:id(.:format)                                                           reviews#update
#                                          DELETE /reviews/:id(.:format)                                                           reviews#destroy
#                         new_user_session GET    /users/sign_in(.:format)                                                         devise/sessions#new
#                             user_session POST   /users/sign_in(.:format)                                                         devise/sessions#create
#                     destroy_user_session DELETE /users/sign_out(.:format)                                                        devise/sessions#destroy
#                  user_omniauth_authorize        /users/auth/:provider(.:format)                                                  devise/omniauth_callbacks#passthru {:provider=>/(?!)/}
#                   user_omniauth_callback        /users/auth/:action/callback(.:format)                                           devise/omniauth_callbacks#(?-mix:(?!))
#                            user_password POST   /users/password(.:format)                                                        devise/passwords#create
#                        new_user_password GET    /users/password/new(.:format)                                                    devise/passwords#new
#                       edit_user_password GET    /users/password/edit(.:format)                                                   devise/passwords#edit
#                                          PUT    /users/password(.:format)                                                        devise/passwords#update
#                 cancel_user_registration GET    /users/cancel(.:format)                                                          devise/registrations#cancel
#                        user_registration POST   /users(.:format)                                                                 devise/registrations#create
#                    new_user_registration GET    /users/sign_up(.:format)                                                         devise/registrations#new
#                   edit_user_registration GET    /users/edit(.:format)                                                            devise/registrations#edit
#                                          PUT    /users(.:format)                                                                 devise/registrations#update
#                                          DELETE /users(.:format)                                                                 devise/registrations#destroy
#                           users_sign_out        /users/sign_out(.:format)                                                        devise/sessions#destroy
#                                dashboard        /dashboard(.:format)                                                             dashboard#dashboard
#                                     root        /                                                                                home#index
#                        group_student_ids GET    /groups/:group_id/student_ids(.:format)                                          student_ids#index
#                                          POST   /groups/:group_id/student_ids(.:format)                                          student_ids#create
#                     new_group_student_id GET    /groups/:group_id/student_ids/new(.:format)                                      student_ids#new
#                    edit_group_student_id GET    /groups/:group_id/student_ids/:id/edit(.:format)                                 student_ids#edit
#                         group_student_id GET    /groups/:group_id/student_ids/:id(.:format)                                      student_ids#show
#                                          PUT    /groups/:group_id/student_ids/:id(.:format)                                      student_ids#update
#                                          DELETE /groups/:group_id/student_ids/:id(.:format)                                      student_ids#destroy
#                          group_tutor_ids GET    /groups/:group_id/tutor_ids(.:format)                                            tutor_ids#index
#                                          POST   /groups/:group_id/tutor_ids(.:format)                                            tutor_ids#create
#                       new_group_tutor_id GET    /groups/:group_id/tutor_ids/new(.:format)                                        tutor_ids#new
#                      edit_group_tutor_id GET    /groups/:group_id/tutor_ids/:id/edit(.:format)                                   tutor_ids#edit
#                           group_tutor_id GET    /groups/:group_id/tutor_ids/:id(.:format)                                        tutor_ids#show
#                                          PUT    /groups/:group_id/tutor_ids/:id(.:format)                                        tutor_ids#update
#                                          DELETE /groups/:group_id/tutor_ids/:id(.:format)                                        tutor_ids#destroy
#                            group_courses GET    /groups/:group_id/courses(.:format)                                              courses#index
#                                          POST   /groups/:group_id/courses(.:format)                                              courses#create
#                         new_group_course GET    /groups/:group_id/courses/new(.:format)                                          courses#new
#                        edit_group_course GET    /groups/:group_id/courses/:id/edit(.:format)                                     courses#edit
#                             group_course GET    /groups/:group_id/courses/:id(.:format)                                          courses#show
#                                          PUT    /groups/:group_id/courses/:id(.:format)                                          courses#update
#                                          DELETE /groups/:group_id/courses/:id(.:format)                                          courses#destroy

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  helper_method :delete_group

    def dashboard
        @user = current_user
        @user_location = Location.where(:user_id => @user.id).first
        @group = Group.new
        @course = @group.build_course
        @organization = Organization.new
        @organizations = Organization.where(:user_id => current_user.id)
        if @organizations.any?
            @programs = Program.where(:organization_id => @organizations.first.id)
        end
        @program = Program.new
        student_id = @group.student_ids.build
        tutor_id = @group.tutor_ids.build
        @tutor_watchlist ||= @user.tutor_watchlist
        
        @tutor_groups = Array.new
        @student_groups = Array.new

        if @user
            @students = Array.new
            User.all.each do |u|
                if u.role? :student 
                    @students << [u.last_name, u.id]
                end
            end

            Group.all.select do |group|
                #groups that user is a tutor for
                group.tutor_ids.all.each do |tutor|
                    if current_user.id == tutor.tid
                        @tutor_groups << group
                    end
                end

                #groups that user is a student in
                group.student_ids.all.each do |student|
                    if current_user.id == student.sid 
                        @student_groups << group 
                    end
                end
            end
        end
        respond_to do |format|
            format.html
        end
    end

    #delete group from database
    def delete_group 
        Group.destroy(params[:id])

        respond_to do |format|
            format.html {redirect_to dashboard_path}
        end
    end
end

app/views/dashboard/_groups_tab.html.erb
<!-- Partial for table of groups -->

<% content_for :header do %>
    <% stylesheet_link_tag 'table_style',:media => :all %>
<% end %>

    <div id='Current_Groups_Table'>
        <%if @tutor_groups.any? %>
        <table class="small_button same_width_buttons">
            <tr>
                <th>Group Name</th>
                <th>Tutors</th>
                <th>Students</th>
<!--                     <th>Courses</th>
                <th>Schedule</th> -->
                <th>Course</th>
                <th>Location</th>
                <th></th>
                <th></th>
            </tr>
            <% @tutor_groups.reverse.each do |group| %>
                <tr>
                    <td><%= link_to group.name, group %>
                        <p><%= group.group_type + ': ' + group.desc[0..28] << "..."%></p></td>

                    <td>
                        <% if group.tutor_ids.empty? %>
                            
                        <% else %>
                        <ul>
                            <% group.tutor_ids.all.each do |tutor| %>
                                <%u = User.find(tutor.tid)%>
                               <li> <%=link_to u.initials, u %></li>
                            <% end %> 
                        </ul>
                        <% end %>
                        
                    </td>
                    <td>
                        <% if group.student_ids.empty? %>
                            -
                         <% else%>
                            <ul>
                            <% group.student_ids.all.each do |student| %>
                                <%u = User.find(student.sid)%>
                                    <li> <%=link_to u.initials, u %></li>
                            <% end %>
                            </ul>
                        <% end %>
                    </td>
                    <td><%= group.course.course_code %></td>
                    <td><%= group.location %></td>
                    <td></td>

                    <% if false %>
                    <td><%= group.courses %></td>
                    <td><%= group.tutor %></td>
                    <td><%= group.student_ids.first %></td>
                    <td><%= group.schedule %></td>
                    <% end %>
                    <td><%= button_to "Edit", edit_group_path(group), :method => :get%><%= button_to "Delete", {:action => :delete_group, :id => group.id}%></td>
                </tr>

            <%end %>
        </table>
            <% else %>
                <p>You don't have any groups yet. Add some!</p>
            <% end %>
    </div>

    <div  class="group_controls">
    <input type='submit' class="create_new" value='Add Group' id='Add Group'/>
    <div id="new_group" style="display:none"><%= render 'groups/form' %></div>
    </div>

app/views/dashboard/_notOrgTab.erb
<div id='not_org'>
	<p>You do not currently manage an Organization.  To register an Organization, please click <a href='signup'>here</a></p>
</div>

app/views/dashboard/_notOrgTab.html.erb
<!-- Partial for user without organization role -->
<div id='not_org'>
	<p>You do not currently manage an Organization.  To register an Organization, please click <%= link_to "here", edit_user_registration_path(current_user) %>.</p>
</div>

app/views/dashboard/_notStudentTab.erb
<div id='not_student'>
				<p>You have not yet activated your Student account.  To register as a Student, please click <a href='signup'>here</a>.
</div>

app/views/dashboard/_notStudentTab.html.erb
<!-- Partial for user without student role -->
<div id='not_student'>
	<p>You have not yet activated your Student account.  To register as a Student, please click <%= link_to "here", edit_user_registration_path(current_user) %>.</p>
</div>

app/views/dashboard/_notTutorTab.erb
<!-- Partial for user without tutor role -->

<div id='not_tutor'>
    <p>You have not yet activated your Tutor account.  To register as a Tutor, please click <%= link_to "here", edit_user_registration_path(current_user) %>.</p>
</div>

app/views/dashboard/_notTutorTab.html.erb
<!-- Partial for user without student role -->

<div id='not_tutor'>
    <p>You have not yet activated your Tutor account.  To register as a Tutor, please click <%= link_to "here", edit_user_registration_path(current_user) %>.</p>
</div>

app/views/dashboard/_orgTab.html.erb
<!-- Partial for user with organization role -->
                    
<div id='Org_Content_View_Options' class="tabs">

	<% if not @organizations.any? %>
    	<div id="new_organization" ><%= render 'organizations/form' %>
    	</div>
    <% end %>
   
    <% if @organizations.any? %>
        <h2 class="inline"><%= @organizations.first.name %>  </h2>
    	<%= link_to "Show", @organizations.first%>
    	<ul class="secondary_tabs">
		   <li><a href="#org_programs">Programs</a></li>
		   <li> <a href="#org_students_tutors" >Students and Tutors</a></li>
    	</ul>

		<div id='org_students_tutors'>
			<p>//Coming soon</p>
		</div>

	<div id='org_programs'>
		<ul class="programs_list">
			<% @programs.each do |program| %>
				<li><%= link_to program do %>
					<h4><%= program.name %></h4>
					<% end %>
					<p>Description:<%= program.desc %></p>
				</li>
			<% end %>
		</ul>
    <%= render 'programs/form' %>
    </div>
	<% end %>
</div>

app/views/dashboard/_studentTab.erb
<div id='student_content_View_Options'>
						<div id='Current_Groups_Button'></div>
						<div id='Watchlist_Button'></div>
				</div>

				<div id='Current_Groups_View'>
					<div id='Add_Group_Button'>
						<form action=''>
							<input type='submit' value='Add Group' id='Add Group'>
						</form>
					</div>

					<div id='Current_Groups_Table'></div>
						<script>
							htmlString='';
							htmlString='<table><tr><th>Group Name</th><th>Courses</th><th>Tutor</th><th>Students</th><th>Schedule</th><th>Location</th><th>Delete</th></tr>';
							for each group in Current_Groups{
								message+='<tr><td>' + group.name+'</td><td>'+group.courses + '</td><td><a href='tuterLink'>group.tutor.name</a></td><td>'' +group.students +'</td><td>'+group.schedule + '</td><td>' + group.schedule + '</td><td>'+group.location + '</td><td><form action='post'><input type=submit value='Remove' id='group.name'>+'</form></td></tr>';
							}
							getElementbyID(Current_Groups_Table).innerHTML=message;
						</script>
					
				</div>


				<div id='Watchlist_View'>
					<div id='Add_Watchlist'>
						<form action=''>
							<input type='submit' value='Add to Watchlist' id='Add to Watchlist' href='/search'>
						</form>
					</div>
					<div id='Watchlist_Table'></div>

						
				</div>";

app/views/dashboard/_studentTab.html.erb
<!-- Partial for user with student role -->

<div class="tabs" id='student_content_View_Options'>
	<ul class="secondary_tabs">
		<li><a href="#current_groups">My Groups</a></li>
		<li><a href="#watchlist">Tutor Watchlist</a></li>
	</ul>


	<div id='current_groups' class="small_button">
		<h2>My Groups</h2>
		<%= render 'student_groups_tab', :groups_type => "student"%>
	</div>


	<div id='watchlist'>
		<h2>Watchlisted Tutors</h2>
		<%if @tutor_watchlist %>
		<ul>
			<% @tutor_watchlist.tutor_ids.each do |t|%>
			<li>
				<% u = User.find(t.tid) if t.tid%>
					<%=link_to u.full_name, u if u%>
			</li>
			<% end %>
		</ul>
		<% end%>
	</div>
	
</div>

app/views/dashboard/_student_groups_tab.html.erb
<!-- Partial for table of student's group-->

<% content_for :header do %>
    <% stylesheet_link_tag 'table_style',:media => :all %>
<% end %>

    <div id='Current_Groups_Table'>
        <%if @student_groups.any? %>
        <table class="small_button">
            <tr>
                <th>Group Name</th>
                <th>Tutors</th>
                <th>Students</th>
<!--                     <th>Courses</th>
                <th>Schedule</th> -->
                <th>Course</th>
                <th>Location</th>
                <th></th>
                <th></th>
            </tr>
            <% @student_groups.reverse.each do |group| %>
                <tr>
                    <td><%= link_to group.name, group %>
                        <p><%= group.group_type + ': ' + group.desc[0..28] << "..." %></p></td>

                    <td>
                        <% if group.tutor_ids.empty? %>
                            
                        <% else %>
                        <ul>
                            <% group.tutor_ids.all.each do |tutor| %>
                                <%u = User.find(tutor.tid)%>
                                    <li> <%= link_to u.initials, u%></li>
                            <% end %> 
                        </ul>
                        <% end %>
                        
                    </td>
                    <td>
                        <% if group.student_ids.empty? %>
                            -
                         <% else%>
                            <ul>
                            <% group.student_ids.all.each do |student| %>
                                <%u = User.find(student.sid)%>
                                   <li> <%= link_to u.initials, u %></li>
                            <% end %>
                            </ul>
                        <% end %>
                    </td>
                    <td><%= group.course.course_code %></td>
                    <td><%= group.location %></td>
                    <td></td>

                    <% if false %>
                    <td><%= group.courses %></td>
                    <td><%= group.tutor %></td>
                    <td><%= group.student_ids.first %></td>
                    <td><%= group.schedule %></td>
                    <% end %>
                </tr>

            <%end %>
        </table>
            <% else %>
                <p>You don't have any groups yet. Add some!</p>
            <% end %>

        <p>To join a group, request a tutor to add you to one</p>
    </div>

app/views/dashboard/_tutorTab.html.erb
<!-- Partial for user with tutor role -->

<%= content_for :header do %>
    <% stylesheet_link_tag 'groups',:media => :all %>
    <% stylesheet_link_tag 'table_style',:media => :all %>
<% end %>

<div class="tabs">
    <ul class="secondary_tabs">
        <li><a href="#groups_view">Groups</a></li>
        <li><a href="#search_students_view">Students</a></li>
    </ul>
    <div id='groups_view'  class="small_button">
        <h2 >My Groups</h2>
        <%= render 'groups_tab', :groups_type => "student" %>
    </div>


    <div id='search_students_view'>
        <h2>Search Students</h2>
        <p>//Coming soon</p>
    </div> 
</div>

app/views/dashboard/dashboard.erb
<%= stylesheet_link_tag    "dashboard", :media => "all" %>

<div id="profile_sidebar">
	<div id="profile_picture"><%= image_tag(current_user.photo, :alt => "Profile Picture") %></div><br/>
	<div id="name"><%=current_user.first_name%> <%=current_user.last_name%></div><br/>
	<div id="affiliation"></div><br/>
	<div id="contact"><a href="mainto:<%=current_user.email%>"><%=current_user.email%></div><br/>
	<div id="social_media"></div><br/>
	<div id="edit_profile">
		<form>
			<input type="submit" name="edit" value="Edit Profile" />
		</form>
	</div><br/>
	<div id="search"></div>
</div>




<div id="center_pane">
	<div id="tabs">

		<div id="student_tab" >
			<% if current_user.student? %>
				<%= render 'studentTab' %>
			<% else %>
				<%= render 'notStudentTab' %>
<			% end %>
		</div>





		<div id="tuter_tab" >
			<% if current_user.tutor? %>
				<%= render 'tutorTab' %>
			<% else %>
				<%= render 'notTutorTab' %>
<			% end %>
		</div>




		<div id="org_tab" >
			<% if current_user.org? %>
				<%= render 'orgTab' %>
			<% else %>
				<%= render 'notOrgTab' %>
<			% end %>
		</div>


	</div>
</div>

app/views/dashboard/dashboard.html.erb
<!-- User dashboard for performing tutor, student or organization functions -->
<% content_for :header do %>
	<%= stylesheet_link_tag "dashboard", :media => "all" %>
	<%= javascript_include_tag "dashboard"%>
	<%= javascript_include_tag "groups"%>
<% end %>

<% if current_user %>
<!-- Profile Sidebar -->
<%= render 'user/user_profile_sidebar' %>

<!-- User Role Tabs -->
<div class="tabs" id="main_tab_container">
	<ul id="main_tabs">
		<li><a href="#student_tab">Student</a></li>
		<li><a href="#tutor_tab">Tutor</a></li>
		<li><a href="#org_tab">Organization</a></li>
	</ul>
	<div id="student_tab" >
		<% if current_user.role? :student %>
			<%= render 'studentTab' %>
		<% else %>
			<%= render 'notStudentTab' %>
		<% end %>
	</div>

	<div id="tutor_tab" >
		<% if current_user.role? :tutor %>
			<%= render 'tutorTab' %>
		<% else %>
			<%= render 'notTutorTab' %>
		<% end %>
	</div>

	<div id="org_tab" >
		<% if current_user.role? :org %>
			<%= render 'orgTab' %>
		<% else %>
			<%= render 'notOrgTab' %>
		<% end %>
	</div>

</div>

<% else %>
	<p>Please <%= link_to "log in", new_session_path(User) %>  to view dashboard. </p>
<% end -%>