config/routes.rb
Tuter::Application.routes.draw do  

  resources :reviews

  devise_for :users
  devise_scope :user do
    match "/users/sign_out" => "devise/sessions#destroy"
    match "/dashboard" => "dashboard#dashboard"
  end

  root :to => "home#index"

  # Android API routes
  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
      get 'tasks' => 'tasks#index', :as => 'tasks'
    end
  end

  resources :groups do
    resources :student_ids
    resources :tutor_ids
    resources :courses
  end

  resources :user
  resources :locations
  resources :search
  resources :organizations
  resources :programs

  resources :tutor_watchlist do
    resources :user
  end

  resources :home do
    member do 
      get 'search_tutors'
    end
  end

  resources :dashboard do
    collection do 
      post 'delete_group'
    end 
  end

  resources :day_availabilities
  
  resources :week_availabilities do
    resources :day_availabilities
    resources :day_availability
  end

  resources :reviews
  
  # Omniauth routes
  match '/users/auth/:provider/callback', to: 'sessions#create'
  match '/users/auth/failure', to: redirect('/')


  # User Signup Routes
  match "/user" => "user#user"
  match "/dashboard" => "home#index"

  # Organization List Page
  match "/organizations" => "organizations#index"
  
  match '/update_watchlist' => 'tutor_watchlist#update' 
 
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
 
  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

#== Route Map
# Generated on 06 May 2013 02:00
#
#                                          POST   /reviews(.:format)                                                               reviews#create
#                               new_review GET    /reviews/new(.:format)                                                           reviews#new
#                              edit_review GET    /reviews/:id/edit(.:format)                                                      reviews#edit
#                                   review GET    /reviews/:id(.:format)                                                           reviews#show
#                                          PUT    /reviews/:id(.:format)                                                           reviews#update
#                                          DELETE /reviews/:id(.:format)                                                           reviews#destroy
#                         new_user_session GET    /users/sign_in(.:format)                                                         devise/sessions#new
#                             user_session POST   /users/sign_in(.:format)                                                         devise/sessions#create
#                     destroy_user_session DELETE /users/sign_out(.:format)                                                        devise/sessions#destroy
#                  user_omniauth_authorize        /users/auth/:provider(.:format)                                                  devise/omniauth_callbacks#passthru {:provider=>/(?!)/}
#                   user_omniauth_callback        /users/auth/:action/callback(.:format)                                           devise/omniauth_callbacks#(?-mix:(?!))
#                            user_password POST   /users/password(.:format)                                                        devise/passwords#create
#                        new_user_password GET    /users/password/new(.:format)                                                    devise/passwords#new
#                       edit_user_password GET    /users/password/edit(.:format)                                                   devise/passwords#edit
#                                          PUT    /users/password(.:format)                                                        devise/passwords#update
#                 cancel_user_registration GET    /users/cancel(.:format)                                                          devise/registrations#cancel
#                        user_registration POST   /users(.:format)                                                                 devise/registrations#create
#                    new_user_registration GET    /users/sign_up(.:format)                                                         devise/registrations#new
#                   edit_user_registration GET    /users/edit(.:format)                                                            devise/registrations#edit
#                                          PUT    /users(.:format)                                                                 devise/registrations#update
#                                          DELETE /users(.:format)                                                                 devise/registrations#destroy
#                           users_sign_out        /users/sign_out(.:format)                                                        devise/sessions#destroy
#                                dashboard        /dashboard(.:format)                                                             dashboard#dashboard
#                                     root        /                                                                                home#index
#                        group_student_ids GET    /groups/:group_id/student_ids(.:format)                                          student_ids#index
#                                          POST   /groups/:group_id/student_ids(.:format)                                          student_ids#create
#                     new_group_student_id GET    /groups/:group_id/student_ids/new(.:format)                                      student_ids#new
#                    edit_group_student_id GET    /groups/:group_id/student_ids/:id/edit(.:format)                                 student_ids#edit
#                         group_student_id GET    /groups/:group_id/student_ids/:id(.:format)                                      student_ids#show
#                                          PUT    /groups/:group_id/student_ids/:id(.:format)                                      student_ids#update
#                                          DELETE /groups/:group_id/student_ids/:id(.:format)                                      student_ids#destroy
#                          group_tutor_ids GET    /groups/:group_id/tutor_ids(.:format)                                            tutor_ids#index
#                                          POST   /groups/:group_id/tutor_ids(.:format)                                            tutor_ids#create
#                       new_group_tutor_id GET    /groups/:group_id/tutor_ids/new(.:format)                                        tutor_ids#new
#                      edit_group_tutor_id GET    /groups/:group_id/tutor_ids/:id/edit(.:format)                                   tutor_ids#edit
#                           group_tutor_id GET    /groups/:group_id/tutor_ids/:id(.:format)                                        tutor_ids#show
#                                          PUT    /groups/:group_id/tutor_ids/:id(.:format)                                        tutor_ids#update
#                                          DELETE /groups/:group_id/tutor_ids/:id(.:format)                                        tutor_ids#destroy
#                            group_courses GET    /groups/:group_id/courses(.:format)                                              courses#index
#                                          POST   /groups/:group_id/courses(.:format)                                              courses#create
#                         new_group_course GET    /groups/:group_id/courses/new(.:format)                                          courses#new
#                        edit_group_course GET    /groups/:group_id/courses/:id/edit(.:format)                                     courses#edit
#                             group_course GET    /groups/:group_id/courses/:id(.:format)                                          courses#show
#                                          PUT    /groups/:group_id/courses/:id(.:format)                                          courses#update
#                                          DELETE /groups/:group_id/courses/:id(.:format)                                          courses#destroy

app/models/week_availability.rb
# == Schema Information
#
# Table name: week_availabilities
#
#  id         :integer          not null, primary key
#  avail_type :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class WeekAvailability < ActiveRecord::Base
  attr_accessible :reference, :avail_type, :day_availabilities, :day_availability_attributes, :user_id

  has_many :day_availabilities
  has_one :user
  accepts_nested_attributes_for :day_availabilities, :allow_destroy => :true
  def self.avail_types
    ['Student', 'Tutor']
  end
end

app/controllers/week_availabilities_controller.rb
class WeekAvailabilitiesController < ApplicationController
  
  
  helper_method :format_time

  # GET /week_availabilities
  # GET /week_availabilities.json
  def index
    @week_availabilities = WeekAvailability.where("user_id = ?", params[:user_id])
    @user = User.find(params[:user_id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @week_availabilities }
    end
  end

  # GET /week_availabilities/1
  # GET /week_availabilities/1.json
  def show
    @week_availability = WeekAvailability.find(params[:id])
    @user = User.find(@week_availability.user_id)
    @days = @week_availability.day_availabilities.sort_by {|d| d.start_time.hour}
    @day_availability = DayAvailability.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @week_availability }
    end
  end

  # GET /week_availabilities/new
  # GET /week_availabilities/new.json
  def new
    @week_availability = WeekAvailability.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @week_availability }
    end
  end

  # GET /week_availabilities/1/edit
  def edit
    @week_availability = WeekAvailability.find(params[:id])
  end

  # POST /week_availabilities
  # POST /week_availabilities.json
  def create
    @week_availability = WeekAvailability.new(params[:week_availability])

    respond_to do |format|
      if @week_availability.save
        format.html { redirect_to @week_availability, notice: 'Week availability was successfully created.' }
        format.json { render json: @week_availability, status: :created, location: @week_availability }
      else
        format.html { render action: "new" }
        format.json { render json: @week_availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /week_availabilities/1
  # PUT /week_availabilities/1.json
  def update
    @week_availability = WeekAvailability.find(params[:id])

    respond_to do |format|
      if @week_availability.update_attributes(params[:week_availability])
        format.html { redirect_to @week_availability, notice: 'Week availability was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @week_availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /week_availabilities/1
  # DELETE /week_availabilities/1.json
  def destroy
    @week_availability = WeekAvailability.find(params[:id])
    @week_availability.destroy

    respond_to do |format|
      format.html { redirect_to week_availabilities_url(:user_id => @week_availability.user_id)}
      format.json { head :no_content }
    end
  end

  def format_time(d)
    zone = Time.zone

    if current_user
      current_user.time_zone
    end

    d.to_time.in_time_zone().strftime(DayAvailability.time_format)
  end
end

app/views/week_availabilities/_form.html.erb
<%= content_for :header do %>
  <%= stylesheet_link_tag "form_style" %>
<% end %>

<%= form_for(@week_availability) do |f| %>  <% if @week_availability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@week_availability.errors.count, "error") %> prohibited this week_availability from being saved:</h2>

      <ul>
      <% @week_availability.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label "Schedule Type" %>
    <%= select(:week_availability, :avail_type, WeekAvailability.avail_types) %>
  </div>

  <%= f.hidden_field :user_id, :value => current_user.id %>


  <div class="actions">
    <label></label>
    <%= f.submit "Update"%>
  </div>
<% end %>

app/views/week_availabilities/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @week_availability %> |
<%= link_to 'Back', week_availabilities_path %>

app/views/week_availabilities/index.html.erb
<%= content_for :header do %>
  <%= stylesheet_link_tag "table_style" %>
<% end %>
<h1>Schedules</h1>

<% if @week_availabilities.any? %>
<table class="schedule">
  <tr>
    <th>Owner</th>
    <th>Type</th>
    <th>Time Slots</th>
    <th>Show</th>

    <% if @user == current_user %>
      <th>Edit</th>
      <th>Delete</th>
    <% end -%>

  </tr>

<% @week_availabilities.each do |w| %>
  <tr>
    <td><%=User.find(w.user_id).last_name %></td>
    <td><%= w.avail_type %></td>
    <td><%= w.day_availabilities.size %></td>
    <td><%= link_to 'Show', w %></td>
    <% if @user == current_user %>
      <td><%= link_to 'Edit', edit_week_availability_path(w) %></td>
      <td><%= link_to 'Delete', w, confirm: 'Are you sure?', method: :delete %></td>
    <% end -%>
  </tr>
<% end %>
</table>
<% else %>
  <p><%= @user.first_name + " " + @user.last_name %> does not have any schedules yet</p>
<% end %>
<br />

<% if current_user and  @user.id == current_user.id %>
  <%= link_to 'New Schedule', new_week_availability_path %>
<% end %>

app/views/week_availabilities/new.html.erb
<h1>New Schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', week_availabilities_path %>

app/views/week_availabilities/show.html.erb
<%= content_for :header do %>
  <%= stylesheet_link_tag "schedule" %>
  <%= javascript_include_tag "schedule" %>
<% end %>
<h2><%=@user.full_name%>'s Schedule</h2>

<div class="new_time_slot">
<%= render 'day_availabilities/form' %>
</div>

<table class="schedule">
    <th>Time/Day</th>
    <% DayAvailability.days.each do |d| %>
    <th><%= d[0].humanize %></th>
    <% end -%>
</table>

<div class="legend">
    <table>
      <tr><td><h3>Legend</h3></td><td class="free">Available</td><td class="busy">Busy</td></tr>
    </table>
</div>

<ul id="days">
<%@days.each do |d| %>
    <li>   
        <% if @user == current_user %>
        <p class="link"><%=link_to edit_week_availability_day_availability_path(@week_availability, d)%>
        <% end -%>
        <p class="day"><%=DayAvailability.days[Integer(d.day)][0]%></p>
        <p class="start_time"><%= format_time(d.start_time)%></p>
        <p class="end_time"><%=format_time(d.end_time)%></p>
        <p class="busy"><%=d.busy?%></p>
    </li>
<% end %>
</ul>   


<%= link_to 'Edit', edit_week_availability_path(@week_availability) %> |
<%= link_to 'Back', user_path(@week_availability.user_id) %>