config/routes.rb
Tuter::Application.routes.draw do  

  resources :reviews

  devise_for :users
  devise_scope :user do
    match "/users/sign_out" => "devise/sessions#destroy"
    match "/dashboard" => "dashboard#dashboard"
  end

  root :to => "home#index"

  # Android API routes
  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
      get 'tasks' => 'tasks#index', :as => 'tasks'
    end
  end

  resources :groups do
    resources :student_ids
    resources :tutor_ids
    resources :courses
  end

  resources :user
  resources :locations
  resources :search
  resources :organizations
  resources :programs

  resources :tutor_watchlist do
    resources :user
  end

  resources :home do
    member do 
      get 'search_tutors'
    end
  end

  resources :dashboard do
    collection do 
      post 'delete_group'
    end 
  end

  resources :day_availabilities
  
  resources :week_availabilities do
    resources :day_availabilities
    resources :day_availability
  end

  resources :reviews
  
  # Omniauth routes
  match '/users/auth/:provider/callback', to: 'sessions#create'
  match '/users/auth/failure', to: redirect('/')


  # User Signup Routes
  match "/user" => "user#user"
  match "/dashboard" => "home#index"

  # Organization List Page
  match "/organizations" => "organizations#index"
  
  match '/update_watchlist' => 'tutor_watchlist#update' 
 
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
 
  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

#== Route Map
# Generated on 06 May 2013 02:00
#
#                                          POST   /reviews(.:format)                                                               reviews#create
#                               new_review GET    /reviews/new(.:format)                                                           reviews#new
#                              edit_review GET    /reviews/:id/edit(.:format)                                                      reviews#edit
#                                   review GET    /reviews/:id(.:format)                                                           reviews#show
#                                          PUT    /reviews/:id(.:format)                                                           reviews#update
#                                          DELETE /reviews/:id(.:format)                                                           reviews#destroy
#                         new_user_session GET    /users/sign_in(.:format)                                                         devise/sessions#new
#                             user_session POST   /users/sign_in(.:format)                                                         devise/sessions#create
#                     destroy_user_session DELETE /users/sign_out(.:format)                                                        devise/sessions#destroy
#                  user_omniauth_authorize        /users/auth/:provider(.:format)                                                  devise/omniauth_callbacks#passthru {:provider=>/(?!)/}
#                   user_omniauth_callback        /users/auth/:action/callback(.:format)                                           devise/omniauth_callbacks#(?-mix:(?!))
#                            user_password POST   /users/password(.:format)                                                        devise/passwords#create
#                        new_user_password GET    /users/password/new(.:format)                                                    devise/passwords#new
#                       edit_user_password GET    /users/password/edit(.:format)                                                   devise/passwords#edit
#                                          PUT    /users/password(.:format)                                                        devise/passwords#update
#                 cancel_user_registration GET    /users/cancel(.:format)                                                          devise/registrations#cancel
#                        user_registration POST   /users(.:format)                                                                 devise/registrations#create
#                    new_user_registration GET    /users/sign_up(.:format)                                                         devise/registrations#new
#                   edit_user_registration GET    /users/edit(.:format)                                                            devise/registrations#edit
#                                          PUT    /users(.:format)                                                                 devise/registrations#update
#                                          DELETE /users(.:format)                                                                 devise/registrations#destroy
#                           users_sign_out        /users/sign_out(.:format)                                                        devise/sessions#destroy
#                                dashboard        /dashboard(.:format)                                                             dashboard#dashboard
#                                     root        /                                                                                home#index
#                        group_student_ids GET    /groups/:group_id/student_ids(.:format)                                          student_ids#index
#                                          POST   /groups/:group_id/student_ids(.:format)                                          student_ids#create
#                     new_group_student_id GET    /groups/:group_id/student_ids/new(.:format)                                      student_ids#new
#                    edit_group_student_id GET    /groups/:group_id/student_ids/:id/edit(.:format)                                 student_ids#edit
#                         group_student_id GET    /groups/:group_id/student_ids/:id(.:format)                                      student_ids#show
#                                          PUT    /groups/:group_id/student_ids/:id(.:format)                                      student_ids#update
#                                          DELETE /groups/:group_id/student_ids/:id(.:format)                                      student_ids#destroy
#                          group_tutor_ids GET    /groups/:group_id/tutor_ids(.:format)                                            tutor_ids#index
#                                          POST   /groups/:group_id/tutor_ids(.:format)                                            tutor_ids#create
#                       new_group_tutor_id GET    /groups/:group_id/tutor_ids/new(.:format)                                        tutor_ids#new
#                      edit_group_tutor_id GET    /groups/:group_id/tutor_ids/:id/edit(.:format)                                   tutor_ids#edit
#                           group_tutor_id GET    /groups/:group_id/tutor_ids/:id(.:format)                                        tutor_ids#show
#                                          PUT    /groups/:group_id/tutor_ids/:id(.:format)                                        tutor_ids#update
#                                          DELETE /groups/:group_id/tutor_ids/:id(.:format)                                        tutor_ids#destroy
#                            group_courses GET    /groups/:group_id/courses(.:format)                                              courses#index
#                                          POST   /groups/:group_id/courses(.:format)                                              courses#create
#                         new_group_course GET    /groups/:group_id/courses/new(.:format)                                          courses#new
#                        edit_group_course GET    /groups/:group_id/courses/:id/edit(.:format)                                     courses#edit
#                             group_course GET    /groups/:group_id/courses/:id(.:format)                                          courses#show
#                                          PUT    /groups/:group_id/courses/:id(.:format)                                          courses#update
#                                          DELETE /groups/:group_id/courses/:id(.:format)                                          courses#destroy

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  group_ID   :integer
#  desc       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  location   :string(255)
#  group_type :string(255)
#

class Group < ActiveRecord::Base
  attr_accessible :desc, :id, :name, :location, :student_ids_attributes, :tutor_ids_attributes, :tutor_ids, 
                  :course, :course_attributes, :group_type
  belongs_to :program
 
  has_many :student_ids
  has_many :tutor_ids
  has_one :course
  after_destroy :cleanup

  validates :name, :location, :group_type, :presence => true
  accepts_nested_attributes_for :student_ids
  accepts_nested_attributes_for :tutor_ids
  accepts_nested_attributes_for :course

  def cleanup
  	self.tutor_ids.destroy_all
  	self.student_ids.destroy_all
  end

  def self.group_types
    ['Drop-In', 'Group', 'One-on-one']
  end

  def students
    students = Array.new
    self.student_ids.all.each do |student|
      students << User.find(student.sid) if student.sid
    end

    students
  end


  def self.json_attributes
    [:id, :name, :location, :group_type, :desc, :course]
  end

  def to_h
    hash = Hash.new
    Group.json_attributes.each do |a|
      hash[a] = self[a]
    end
    hash
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def index
		@groups = Group.all
		@group = Group.find(params[:id])
		@students = Student_id.find(:id => params[:id])
		@tutors = User.find(params[:tutor_ids])
		#@tids = params[:tutor_ids].each { |tid| }

		respond_to do |format|
			format.html
		end
	end

	def new
		@group = Group.new
		@course = @group.build_course
		student_id = @group.student_ids.build
		tutor_id = @group.tutor_ids.build

		respond_to do |format|
			format.html
		end
	end

	def create
		@group = Group.new(params[:group])

		respond_to do |format|
			if @group.save
				format.html { redirect_to dashboard_path }
			end	
		end
	end 

	def show
		@group = Group.find(params[:id])
		@students = StudentId.all_students

		respond_to do |format|
			format.html
			format.json { render :json => group_to_json(@group)}
		end
	end

	def group_to_json(group)
		# @group.to_json(:include => [:course, :student_ids, :tutor_ids])
		hash = group.to_h

		course = 
		{
			:course_name => group.course.name,
			:course_code => group.course.course_code,
		}

		tutors = Array.new

		group.tutor_ids.each do |t|
			u = User.find(t.tid)
			tutors << u.to_h
		end

		students = Array.new

		group.student_ids.each do |t|
			u = User.find(t.sid)
			students << u.to_h
		end

		hash[:course] = course
		hash[:students] = students
		hash[:tutors] = tutors

		hash
	end

	def destroy
		@group = Group.find(params[:id])

		@group.destroy 

		respond_to do |format|
			format.html { redirect_to groups_url }
		end

	end

	def edit
		@students = StudentId.all_students
		@group = Group.find(params[:id])
		student_id = @group.student_ids

		if not student_id
			student_id = @group.student_ids.build
		end

		respond_to do |format|
			format.html
		end
	end

	def update
		@group = Group.find(params[:id])
		@course = @group.course

		@group.update_attributes(params[:group])
		respond_to do |format|
			format.html {redirect_to dashboard_path}
		end
	end
end

app/views/groups/_form.html.erb
<%= content_for :header do %>
    <%= stylesheet_link_tag 'form_style', :media => "all" %>
<% end %>
<h3> Create New Group </h3>
<%= form_for(@group) do |f| %>
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, :placeholder => "e.g. Small Biology Group"%>
    </div>

    <div class="field">
        <%= f.label 'Description' %>
        <%= f.text_area :desc, :class=>'narrow'%>

    </div>    <div class="field ">
        <%= f.label 'Group Type' %>
        <%= select(:group, :group_type, Group.group_types)%>
    </div>

    <div class="field">
        <%= f.label :location %>
        <%= f.text_field :location, :placeholder => "e.g. Helen C White" %>
    </div>  

    <div class="field">
        <%= f.fields_for :tutor_ids do |tutorBuilder| %>
            <%= render "groups/tutorFields", :f => tutorBuilder %>
        <% end %>
    </div>

    <%= f.fields_for :course do |c|%>
        <div class="field">
          <%= c.label "Course Title" %>
          <%= c.text_field :name, :placeholder => "e.g. Introduction of Biology"%>
        </div>
        <div class="field">
          <%= c.label "Course Code" %>
          <%= c.text_field :course_code, :placeholder => "e.g. BIO 101" %>
        </div>
    <% end %>

	<div class="actions small_button float_right">
    	<%= f.submit %>
  	</div>

    <div class="actions small_button float_left">
        <%= button_to "Cancel", {}, :class => "cancel", :id=>"cancel_create" %>
    </div>
<% end %>

app/views/groups/_studentFields.html.erb
<div>
<%= f.label "Student" %>
<%= f.select(:sid, @students, {:include_blank => true}) %>
</div>

app/views/groups/_tutorFields.html.erb
<%= f.hidden_field :tid, :value => current_user.id %>

app/views/groups/edit.html.erb
<h1>Edit group</h2>
    <%= render 'form' %>

<h3>Add Students</h3>
<ul>
    <%@group.students.each do |s|%>
        <li><%= link_to s.full_name, s %></li>
    <% end -%>
</ul>
<%= form_for [@group, @group.student_ids.build] do |f|%>
    <%= render "studentFields", :f=> f%>
    <div class="small_button">
        <label></label>
        <%= f.submit "Add Student"%>
    </div>
<% end -%>

app/views/groups/index.html.erb
<% content_for :header do %>
    <%= stylesheet_link_tag "groups", :media => "all" %>
    <%= javascript_include_tag "groups", :media => "all" %>
<% end %>
<h1> My Groups</h1>
<div class="group">
    <ul>
    <%- @groups.each do |group| %>
    <!--Don't show groups without names -->
        <% if group.name.length > 0 %>
            <li><strong><%= group.name %></strong>
                <p><% if group.desc %>
                        <%= group.desc %>
                    <% else %>
                        No description
                    <% end %>
                </p></li>
        <% end %>
    <% end%>
    </ul>
</div>
<div id="buttons">
    <input type="button" id="create_new" value="Create New"></input>
    <input type="input" id="search" placeholder="Search Groups">
</div>
<div id="new_group" style="display:none"><%= render 'new' %></div>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<%= content_for :header do %>
    <%= stylesheet_link_tag 'groups' %>
    <%= stylesheet_link_tag 'form_style' %>
<% end %>
<div class="single_group">

<div>
    <h2><%= @group.name.humanize %></h2>
</div>

<div>
    <h3>Course </h3>
    <ul><li><%= @group.course.course_code%> - <%= @group.course.name %></li></ul>
</div>

<div>
    <h3>Location</h3>
    <ul><li><%= @group.location %></li></ul>
</div>

<div>
    <h3>Tutors</h3>
    <ul>
    <% @group.tutor_ids.all.each do |tutor| %>
        <% if tutor.tid  %>
        <%u = User.find(tutor.tid) %>
        <li><%= link_to  u.full_name, u%></li>
    <% end %>
    <% end %>
    </ul>
</div>

<div>
    <h3>Students</h3>
    <ul>
        <%@group.students.each do |s|%>
        <% if s  %>
            <li><%= link_to s.full_name, s %></li>
        <% end -%>
        <% end -%>
    </ul>
</div>

<br />
<%= link_to "Edit Group", edit_group_path(@group) %> | <%= link_to "Delete Group", @group, method: :delete %>

</div>