config/routes.rb
Tuter::Application.routes.draw do  

  resources :reviews

  devise_for :users
  devise_scope :user do
    match "/users/sign_out" => "devise/sessions#destroy"
    match "/dashboard" => "dashboard#dashboard"
  end

  root :to => "home#index"

  # Android API routes
  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
      get 'tasks' => 'tasks#index', :as => 'tasks'
    end
  end

  resources :groups do
    resources :student_ids
    resources :tutor_ids
    resources :courses
  end

  resources :user
  resources :locations
  resources :search
  resources :organizations
  resources :programs

  resources :tutor_watchlist do
    resources :user
  end

  resources :home do
    member do 
      get 'search_tutors'
    end
  end

  resources :dashboard do
    collection do 
      post 'delete_group'
    end 
  end

  resources :day_availabilities
  
  resources :week_availabilities do
    resources :day_availabilities
    resources :day_availability
  end

  resources :reviews
  
  # Omniauth routes
  match '/users/auth/:provider/callback', to: 'sessions#create'
  match '/users/auth/failure', to: redirect('/')


  # User Signup Routes
  match "/user" => "user#user"
  match "/dashboard" => "home#index"

  # Organization List Page
  match "/organizations" => "organizations#index"
  
  match '/update_watchlist' => 'tutor_watchlist#update' 
 
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
 
  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

#== Route Map
# Generated on 06 May 2013 02:00
#
#                                          POST   /reviews(.:format)                                                               reviews#create
#                               new_review GET    /reviews/new(.:format)                                                           reviews#new
#                              edit_review GET    /reviews/:id/edit(.:format)                                                      reviews#edit
#                                   review GET    /reviews/:id(.:format)                                                           reviews#show
#                                          PUT    /reviews/:id(.:format)                                                           reviews#update
#                                          DELETE /reviews/:id(.:format)                                                           reviews#destroy
#                         new_user_session GET    /users/sign_in(.:format)                                                         devise/sessions#new
#                             user_session POST   /users/sign_in(.:format)                                                         devise/sessions#create
#                     destroy_user_session DELETE /users/sign_out(.:format)                                                        devise/sessions#destroy
#                  user_omniauth_authorize        /users/auth/:provider(.:format)                                                  devise/omniauth_callbacks#passthru {:provider=>/(?!)/}
#                   user_omniauth_callback        /users/auth/:action/callback(.:format)                                           devise/omniauth_callbacks#(?-mix:(?!))
#                            user_password POST   /users/password(.:format)                                                        devise/passwords#create
#                        new_user_password GET    /users/password/new(.:format)                                                    devise/passwords#new
#                       edit_user_password GET    /users/password/edit(.:format)                                                   devise/passwords#edit
#                                          PUT    /users/password(.:format)                                                        devise/passwords#update
#                 cancel_user_registration GET    /users/cancel(.:format)                                                          devise/registrations#cancel
#                        user_registration POST   /users(.:format)                                                                 devise/registrations#create
#                    new_user_registration GET    /users/sign_up(.:format)                                                         devise/registrations#new
#                   edit_user_registration GET    /users/edit(.:format)                                                            devise/registrations#edit
#                                          PUT    /users(.:format)                                                                 devise/registrations#update
#                                          DELETE /users(.:format)                                                                 devise/registrations#destroy
#                           users_sign_out        /users/sign_out(.:format)                                                        devise/sessions#destroy
#                                dashboard        /dashboard(.:format)                                                             dashboard#dashboard
#                                     root        /                                                                                home#index
#                        group_student_ids GET    /groups/:group_id/student_ids(.:format)                                          student_ids#index
#                                          POST   /groups/:group_id/student_ids(.:format)                                          student_ids#create
#                     new_group_student_id GET    /groups/:group_id/student_ids/new(.:format)                                      student_ids#new
#                    edit_group_student_id GET    /groups/:group_id/student_ids/:id/edit(.:format)                                 student_ids#edit
#                         group_student_id GET    /groups/:group_id/student_ids/:id(.:format)                                      student_ids#show
#                                          PUT    /groups/:group_id/student_ids/:id(.:format)                                      student_ids#update
#                                          DELETE /groups/:group_id/student_ids/:id(.:format)                                      student_ids#destroy
#                          group_tutor_ids GET    /groups/:group_id/tutor_ids(.:format)                                            tutor_ids#index
#                                          POST   /groups/:group_id/tutor_ids(.:format)                                            tutor_ids#create
#                       new_group_tutor_id GET    /groups/:group_id/tutor_ids/new(.:format)                                        tutor_ids#new
#                      edit_group_tutor_id GET    /groups/:group_id/tutor_ids/:id/edit(.:format)                                   tutor_ids#edit
#                           group_tutor_id GET    /groups/:group_id/tutor_ids/:id(.:format)                                        tutor_ids#show
#                                          PUT    /groups/:group_id/tutor_ids/:id(.:format)                                        tutor_ids#update
#                                          DELETE /groups/:group_id/tutor_ids/:id(.:format)                                        tutor_ids#destroy
#                            group_courses GET    /groups/:group_id/courses(.:format)                                              courses#index
#                                          POST   /groups/:group_id/courses(.:format)                                              courses#create
#                         new_group_course GET    /groups/:group_id/courses/new(.:format)                                          courses#new
#                        edit_group_course GET    /groups/:group_id/courses/:id/edit(.:format)                                     courses#edit
#                             group_course GET    /groups/:group_id/courses/:id(.:format)                                          courses#show
#                                          PUT    /groups/:group_id/courses/:id(.:format)                                          courses#update
#                                          DELETE /groups/:group_id/courses/:id(.:format)                                          courses#destroy

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  first_name             :string(255)
#  last_name              :string(255)
#  desc                   :text
#  uid                    :integer
#  provider               :string(255)
#  oauth_token            :string(255)
#  oauth_expires_at       :datetime
#  photo                  :string(255)
#  fb_profile             :string(255)
#  roles_mask             :integer
#  course_ID              :integer
#  age                    :integer
#  year                   :string(255)
#  transportation         :string(255)
#  rate                   :string(255)
#  time_zone              :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, 
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable,
         :recoverable, :rememberable, :trackable, :omniauthable, :token_authenticatable

  has_one :location
  has_one :tutor_watchlist
  has_many :courses
  has_one :organization

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :photo, 
                  :first_name, :last_name, :desc, :provider, :uid, :roles, :location, :location_attributes,
                  :age, :transportation, :year, :courses, :courses_attributes, :rate, :time_zone,
                  :tutor_watchlist

  before_save :ensure_authentication_token


  # Setup creation validation
  # Devise's default => :email and :password must be present 
  validates :first_name, :last_name, :presence => true

  # https://github.com/ryanb/cancan/wiki/Role-Based-Authorization
  # define user roles and association
  ROLES = %w[student tutor org]
  has_and_belongs_to_many :roles

  accepts_nested_attributes_for :courses

  def self.years
    ['Freshman', 'Sophomore', 'Junior', 'Senior', 'Graduate', 'Others']
  end
  
  def full_name
    self.first_name + " " + self.last_name
  end

  def initials
    self.first_name[0] + self.last_name[0]
  end

  def self.age_range
    18..80
  end

  def with_course
    self.courses.build
    self
  end

  def self.json_attributes
    [:id, :first_name, :last_name, :age, :year, :email,
          :photo, :desc, :roles, :rate,:tutor_watchlist]
  end

  def self.rates 
    rates = Array.new
    start_rate  = 0
    end_rate    = 100
    interval    = 10
    i = start_rate

    until end_rate < i
        rates.push("$#{i} - $#{i + interval}")
        i += interval
    end
    rates
  end

  def self.from_omniauth(auth)
  	where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
  		user.provider = auth.provider
  		user.uid = auth.uid
  		user.email = auth.info.email
  		user.first_name = auth.info.first_name
  		user.last_name = auth.info.last_name
      user.photo = auth.info.image
      user.fb_profile = auth.info.urls.Facebook
  		user.oauth_token = auth.credentials.token 
  		user.oauth_expires_at  = Time.at(auth.credentials.expires_at) 
  		user.save!
  	end	
  end 

  def password_required?
    super && provider.blank?
  end

  # update user attributes - handles omniauth users without passwords, as well as devise users with passwords
  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes!(params, *options)
    else
      super
    end
  end

  # check if user has a given role
  def role?(role)
    roles.include? role.to_s
  end

  # return list of symbols that represent user roles
  def role_symbols
    roles.map do |role|
      role.name.to_sym
    end
  end

  # http://asciicasts.com/episodes/189-embedded-association
  # define user bitmask to represent which roles the user has
  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask || 0) & 2**ROLES.index(r)).zero?
    end
  end

  def roles_to_h
    hash = Hash.new
    self.roles.each_with_index{|role, index|
      hash[role] = true
    }

    hash.to_json
  end

  def courses
    courses = Array.new
     # add courses that tutor has 
    Group.all.select do |group|
      group.tutor_ids.all.each do |tutor|
        if (self.id == tutor.tid) and group.course 
            courses << group.course.to_h
        end
      end
    end
    courses
  end 

  def to_h
    hash = Hash.new
    User.json_attributes.each do |a|
      hash[a] = self[a]
    end
    # add location

    hash
  end

  def skip_confirmation!
    self.confirmed_at = Time.now
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  helper_method :user_average_rating
  def show
    @user = User.find(params[:id])
    @user_location = Location.find(@user.location_ID)
    @users_groups = Array.new

    #select user's groups
    Group.all.select do |group|
      #groups that user is a tutor for
      group.tutor_ids.all.each do |tutor|
          if @user.id == tutor.tid
              @users_groups << group
          end
      end
    end
    @review = Review.new

    @reviews= Review.where(:user_id => @user.id)

    respond_to do |format|
        format.html
        format.json {render :json => user_as_json(@user, @users_groups, @user_location)}#:json => @user.to_json(:method => groups_as_json(@users_groups), :only => User.json_attributes)}
    end
  end

  def user_as_json (user, users_groups, loc)

    json = user.to_h

    groups_json = users_groups.collect do |group|
      {
        :name   => group.name,
        :id     => group.id,
        :desc   => group.desc,
        :course => 
          {
            :course_name => group.course.name,
            :course_code => group.course.course_code
          }
      }
    end

    json.merge :location => loc.to_h, :groups => groups_json

  end

  def user_average_rating
    total_stars = 0

    @reviews.each do |r|
      total_stars += r.rating
    end

    average_rating = total_stars / @reviews.size
  end
end

app/views/user/_rating_stars.html.erb
 <% width = '12px'%>
 <% width = '20px' if size == "large"%>
 <% stars.times do %>
    <%= image_tag("/images/rating_star.png", :width => width) %>
<%end%>

<% (Review.rating_range.last - stars).times do %>
    <%= image_tag("/images/rating_star_unselected.png", :width => width) %>
<% end -%>

app/views/user/_user_groups.html.erb
<div id ="users_groups">  
<h1>Tutoring Groups</h1>  
    <% if not @users_groups.any? or not @user.role? :tutor%>
        <p>User does not tutor any groups </p>
    <% end -%>
    <ul class="groups_list">
    <% @users_groups.each do |g| %>
        <li>
            <h3><%=link_to g.name, g %><span> - <%=g.course.name%></span></h3>
            <p class="float_right"><span>Tutors: <%= g.tutor_ids.size %>, </span><span>Students: <%= g.student_ids.size %></span></p>
            <p><strong><%=g.group_type %>. </strong><%= g.desc %></p>
        </li>
    <% end %>
    </ul>

</div>

app/views/user/_user_location.html.erb
<%= gmaps4rails(@user_location.to_gmaps4rails) %>

app/views/user/_user_profile_sidebar.html.erb
<!-- Partial for user profile sidebar. Displays user's personal information -->
<% content_for :header do %>
    <% stylesheet_link_tag "user_profile", :media => "all" %>
<% end %>
<div id="profile">
    <!-- Display User Profile Picture-->
    <% if @user.photo? %>
        <%= link_to image_tag(@user.photo, :alt => "Profile Picture"), @user %>
    <% else %>
        <%= link_to image_tag("/images/def_profile_pic.jpg", :alt => "Profile Picture"), @user%>
    <% end %>

    <h2><%=@user.first_name %> <%=@user.last_name %></h2>
    <p><%=@user.desc %></p>


    <h3>Personal Information</h3>
    <div>
    <% if @user.age? %>
        <%=@user.age %> years old,
    <% end %>    
    <% if @user.year? %>
        <%=@user.year %>
        <br />
    <% end -%>
    <% if @user_location %>
        <% if @user == current_user %>
            <%= link_to edit_location_path(@user_location) do %>
            <span class="address"><%= @user_location.address.split(',').join('<br/>').html_safe%></span>
            <% end %>
            <% else %>
            <span class="address"><%= @user_location.address.split(',').join('<br/>').html_safe%></span>
        <% end %>
    <% elsif @user == current_user%>
        <br />
        <%= link_to "Add Location", new_location_path %>
    <% end %>
    </div>
    <!-- <div>Transportation: Bus, Walk</div>
    <div>Tutor Rating: <a>**** (4)</a></div>
 -->
    <h3>Roles</h3>
    <ul>
        <% if @user.role? :student %> <li>Student</li> <% end %>
        <% if @user.role? :tutor %><li>Tutor</li> <% end %>
        <% if @user.role? :org %> <li>Organization</li><% end %>
    </ul>

    <h3>Contact Info</h3>
    <div><a href="mailto:<%=@user.email%>"><%= @user.email %></a></div>
    <div><% if @user.fb_profile %><%= link_to "Facebook Profile", @user.fb_profile %><% end %></div>
    <!-- Button to edit user profile -->
    <h3>Schedule</h3>
    <%= link_to "View", week_availabilities_path(:user_id => @user.id) %>

    <!-- Only display edit user option for own profile -->
    <% if current_user and @user.id == current_user.id %>
    <div class="small_button unimp">
    <%= button_to "Edit Profile", edit_user_registration_path(@user), :method=> :get %>
    </div>
    <% end %>

</div>

app/views/user/_user_reviews.html.erb
<% content_for :header do %>
    <% stylesheet_link_tag "reviews", :media => "all" %>
<% end %>
<div id="reviews">
<h1>Reviews</h1>
    <% if @user.role? :tutor %>
        <% if @reviews.any? %>
            <h3>Average Rating: <%= user_average_rating %>/5</h3>
        <% end %>
        <ul>
            <% @reviews.each do |r| %>
                <li>
                    <h4><%= r.title %></h4>
                    <p class="review">
                    <span class="review_rating">
                        <% r.rating.times do %>
                        <%= image_tag("/images/rating_star.png", :width => '12px') %>
                        <%end%>

                        <% (Review.rating_range.last - r.rating).times do %>
                        <%= image_tag("/images/rating_star_unselected.png", :width => '12px') %>
                        <% end -%>
                    </span>
                    <span class="review_content"><%= r.content%></span>
                    <% if r.recommend %>
                        <span class="review_recommended">Recommended Tutor.<br/></span>
                    <% end %>
                    <span class="review_reviewer">by 
                        <%= link_to user_path :id=> r.reviewer_id do %>
                        <%= User.find(r.reviewer_id).full_name %>
                        <% end %></span>
                    </span><span class="time"><%= r.created_at.to_time.in_time_zone(Time.zone).strftime("%d %b %Y")%></span></p>
                    <% if current_user and r.reviewer_id.equal?(current_user.id) %>
                    <div class="small_button unimp button_group">
                        <%= button_to "Delete", r,:data => { :confirm => "Are you sure?" }, :method => :delete %>
                    </div>
                    <% end %>
                </li>
            <% end %>
        </ul>
    <% if current_user == @user%>
        <!-- Don't allow users to add reviews for themselves -->
    <% elsif current_user %>
        <div class="new_review">
            <h3>Add Review</h3>
            <%= render "reviews/form" %>
        </div>
    <% else %>
        <h3> Log In to add a review. </h3>
    <% end %>
<% else %> <p>This user is not a tutor</p>
    <% end %>
</div>

app/views/user/show.html.erb
<%= content_for :header do%>
  <%= stylesheet_link_tag "gmaps4rails", :media => "all" %>
  <%= javascript_include_tag "gmaps4rails/gmaps4rails.base", 
                             "gmaps4rails/gmaps4rails.googlemaps",
                             "gmaps_curr_location" %>
<% end %>

<%= render 'user_profile_sidebar' %>
<div id="reviews_container">

<div id="add_to_watchlist">
    <% if @user.role? :tutor and current_user%>
        <p>Like this tutor? Add them to your <%= link_to "watchlist!", {:controller => "tutor_watchlist", :action => "update", :tutor_id => @user.id, :user_id => current_user.id}, :method => :put %></p>
    <% end %>
</div>
    <%if @user_location %>
        <%= render 'user_location' %>
    <% end -%>
    <%= render 'user_groups' %>
    <%= render 'user_reviews' %>
</div>